apiVersion: v2
version: 2.11.0-main-unstable-2026-01-21-00-34-05
name: openebs
appVersion: 2.11.0-main-unstable-2026-01-21-00-34-05
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: https://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-crds
    version: 4.5.0-develop
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: alloy
    version: 1.0.1
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: localpv-provisioner
    version: 4.5.0-develop
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
  - name: zfs-localpv
    version: 2.10.0-develop
    repository: "https://openebs.github.io/zfs-localpv"
    condition: engines.local.zfs.enabled
  - name: lvm-localpv
    version: 1.9.0-develop
    repository: "https://openebs.github.io/lvm-localpv"
    condition: engines.local.lvm.enabled
  - name: rawfile-localpv
    version: 0.12.0
    repository: "https://openebs.github.io/rawfile-localpv"
    condition: engines.local.rawfile.enabled
  - name: mayastor
    version: 2.11.0-main-unstable-2026-01-21-00-34-05
    repository: https://openebs.github.io/mayastor-chart-donotuse
    condition: engines.replicated.mayastor.enabled

annotations:
  helm.sh/images: |
    - name: alloy
      image: docker.io/grafana/alloy:v1.8.1
    - name: loki
      image: docker.io/grafana/loki:3.4.2
    - name: k8s-sidecar
      image: docker.io/kiwigrid/k8s-sidecar:1.30.2
    - name: nats
      image: docker.io/nats:2.9.17-alpine
    - name: nats-box
      image: docker.io/natsio/nats-box:0.13.8
    - name: nats-server-config-reloader
      image: docker.io/natsio/nats-server-config-reloader:0.10.1
    - name: prometheus-nats-exporter
      image: docker.io/natsio/prometheus-nats-exporter:0.11.0
    - name: alpine-bash
      image: docker.io/openebs/alpine-bash:4.3.0
    - name: alpine-sh
      image: docker.io/openebs/alpine-sh:4.3.0
    - name: etcd
      image: docker.io/openebs/etcd:3.6.4-debian-12-r0
    - name: kubectl
      image: docker.io/openebs/kubectl:1.25.15
    - name: linux-utils
      image: docker.io/openebs/linux-utils:4.3.0
    - name: lvm-driver
      image: docker.io/openebs/lvm-driver:1.9.0-develop
    - name: mayastor-agent-core
      image: docker.io/openebs/mayastor-agent-core:develop
    - name: mayastor-agent-ha-cluster
      image: docker.io/openebs/mayastor-agent-ha-cluster:develop
    - name: mayastor-agent-ha-node
      image: docker.io/openebs/mayastor-agent-ha-node:develop
    - name: mayastor-api-rest
      image: docker.io/openebs/mayastor-api-rest:develop
    - name: mayastor-csi-controller
      image: docker.io/openebs/mayastor-csi-controller:develop
    - name: mayastor-csi-node
      image: docker.io/openebs/mayastor-csi-node:develop
    - name: mayastor-io-engine
      image: docker.io/openebs/mayastor-io-engine:develop
    - name: mayastor-metrics-exporter-io-engine
      image: docker.io/openebs/mayastor-metrics-exporter-io-engine:develop
    - name: mayastor-obs-callhome-stats
      image: docker.io/openebs/mayastor-obs-callhome-stats:develop
    - name: mayastor-obs-callhome
      image: docker.io/openebs/mayastor-obs-callhome:develop
    - name: mayastor-operator-diskpool
      image: docker.io/openebs/mayastor-operator-diskpool:develop
    - name: provisioner-localpv
      image: docker.io/openebs/provisioner-localpv:4.4.0
    - name: provisioner-localpv
      image: docker.io/openebs/provisioner-localpv:4.5.0-develop
    - name: rawfile-localpv
      image: docker.io/openebs/rawfile-localpv:v0.12.0
    - name: zfs-driver
      image: docker.io/openebs/zfs-driver:2.10.0-develop
    - name: mc
      image: quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z
    - name: minio
      image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    - name: prometheus-config-reloader
      image: quay.io/prometheus-operator/prometheus-config-reloader:v0.81.0
    - name: csi-attacher
      image: registry.k8s.io/sig-storage/csi-attacher:v4.8.1
    - name: csi-node-driver-registrar
      image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
    - name: csi-provisioner
      image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
    - name: csi-resizer
      image: registry.k8s.io/sig-storage/csi-resizer:v1.11.2
    - name: csi-resizer
      image: registry.k8s.io/sig-storage/csi-resizer:v1.13.2
    - name: csi-snapshotter
      image: registry.k8s.io/sig-storage/csi-snapshotter:v7.0.0
    - name: csi-snapshotter
      image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
    - name: csi-snapshotter
      image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
    - name: snapshot-controller
      image: registry.k8s.io/sig-storage/snapshot-controller:v7.0.0
    - name: snapshot-controller
      image: registry.k8s.io/sig-storage/snapshot-controller:v8.2.0
    - name: snapshot-controller
      image: registry.k8s.io/sig-storage/snapshot-controller:v8.2.1
