apiVersion: v2
version: 4.3.4-prerelease
name: openebs
appVersion: 4.3.4-prerelease
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: https://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-crds
    version: 4.3.4-prerelease
  - name: loki
    version: 6.29.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: alloy
    version: 1.0.1
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: localpv-provisioner
    version: 4.3.0
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
  - name: zfs-localpv
    version: 2.8.0
    repository: "https://openebs.github.io/zfs-localpv"
    condition: engines.local.zfs.enabled
  - name: lvm-localpv
    version: 1.7.0
    repository: "https://openebs.github.io/lvm-localpv"
    condition: engines.local.lvm.enabled
  - name: mayastor
    version: 2.9.2
    repository: "https://openebs.github.io/mayastor-extensions"
    condition: engines.replicated.mayastor.enabled

annotations:
  helm.sh/images: |
    - name: alloy
      image: docker.io/grafana/alloy:v1.8.1
    - name: loki
      image: docker.io/grafana/loki:3.4.2
    - name: alpine-bash
      image: docker.io/openebs/alpine-bash:4.2.0
    - name: alpine-sh
      image: docker.io/openebs/alpine-sh:4.2.0
    - name: etcd
      image: docker.io/openebs/etcd:3.5.6-debian-11-r10
    - name: kubectl
      image: docker.io/openebs/kubectl:1.25.15
    - name: mayastor-agent-core
      image: docker.io/openebs/mayastor-agent-core:v2.9.2
    - name: mayastor-agent-ha-cluster
      image: docker.io/openebs/mayastor-agent-ha-cluster:v2.9.2
    - name: mayastor-agent-ha-node
      image: docker.io/openebs/mayastor-agent-ha-node:v2.9.2
    - name: mayastor-api-rest
      image: docker.io/openebs/mayastor-api-rest:v2.9.2
    - name: mayastor-csi-controller
      image: docker.io/openebs/mayastor-csi-controller:v2.9.2
    - name: mayastor-csi-node
      image: docker.io/openebs/mayastor-csi-node:v2.9.2
    - name: mayastor-io-engine
      image: docker.io/openebs/mayastor-io-engine:v2.9.2
    - name: mayastor-metrics-exporter-io-engine
      image: docker.io/openebs/mayastor-metrics-exporter-io-engine:v2.9.2
    - name: mayastor-obs-callhome-stats
      image: docker.io/openebs/mayastor-obs-callhome-stats:v2.9.2
    - name: mayastor-obs-callhome
      image: docker.io/openebs/mayastor-obs-callhome:v2.9.2
    - name: mayastor-operator-diskpool
      image: docker.io/openebs/mayastor-operator-diskpool:v2.9.2
    - name: k8s-sidecar
      image: kiwigrid/k8s-sidecar:1.30.2
    - name: nats
      image: nats:2.9.17-alpine
    - name: nats-box
      image: natsio/nats-box:0.13.8
    - name: nats-server-config-reloader
      image: natsio/nats-server-config-reloader:0.10.1
    - name: prometheus-nats-exporter
      image: natsio/prometheus-nats-exporter:0.11.0
    - name: linux-utils
      image: openebs/linux-utils:4.2.0
    - name: lvm-driver
      image: openebs/lvm-driver:1.7.0
    - name: provisioner-localpv
      image: openebs/provisioner-localpv:4.3.0
    - name: zfs-driver
      image: openebs/zfs-driver:2.8.0
    - name: mc
      image: quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z
    - name: minio
      image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    - name: prometheus-config-reloader
      image: quay.io/prometheus-operator/prometheus-config-reloader:v0.81.0
    - name: csi-attacher
      image: registry.k8s.io/sig-storage/csi-attacher:v4.8.1
    - name: csi-node-driver-registrar
      image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
    - name: csi-provisioner
      image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
    - name: csi-resizer
      image: registry.k8s.io/sig-storage/csi-resizer:v1.11.2
    - name: csi-resizer
      image: registry.k8s.io/sig-storage/csi-resizer:v1.13.2
    - name: csi-snapshotter
      image: registry.k8s.io/sig-storage/csi-snapshotter:v7.0.0
    - name: csi-snapshotter
      image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
    - name: snapshot-controller
      image: registry.k8s.io/sig-storage/snapshot-controller:v7.0.0
    - name: snapshot-controller
      image: registry.k8s.io/sig-storage/snapshot-controller:v8.2.0
